apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-deploy.fullname" . }}
  labels:
    {{- include "helm-deploy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-deploy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-deploy.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: wordpress
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: WORDPRESS_DB_HOST
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.externalDatabase.secret_name }}"
                key: "{{ .Values.externalDatabase.host }}"
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.externalDatabase.secret_name }}"
                key: "{{ .Values.externalDatabase.database }}"
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.externalDatabase.secret_name }}"
                key: "{{ .Values.externalDatabase.user }}"
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.externalDatabase.secret_name }}"
                key: "{{ .Values.externalDatabase.password }}"
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # volumeMounts:
          # - name: wordpress-persistent-storage
          #   mountPath: /var/www/html
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      # volumes:
      # - name: wordpress-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: wp-pv-claim
