apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "helm-deploy.fullname" . }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: {{ include "helm-deploy.fullname" . }}