apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wplearndev
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: wplearndev
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wplearndev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wplearndev
spec:
  selector:
    matchLabels:
      app: wplearndev
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wplearndev
        tier: frontend
    spec:
      containers:
      - name: wordpress
        image: poornimak/wordpressapp:1.0
        env:
        - name: MYSQLDB_HOST
          value: mysqldb
        - name: MYSQLDB_PORT
          value: "3306"
        - name: WORDPRESS_DATABASE_USER
          value: wordpress_user
        - name: WORDPRESS_DATABASE_NAME
          value: wordpress
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqldb
              key: password
        - name: WORDPRESS_USERNAME
          value: admin
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: password
        - name: WORDPRESS_BLOG_NAME
          value: WP L&D App
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
