apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  namespace: poornima-dev
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: poornimak/phpwpapp:1.1
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: wplearndev-rds-output
              key: rds_instance_endpoint
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wplearndev-rds-output
              key: database_name
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wplearndev-rds-output
              key: database_username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wplearndev-rds-output
              key: database_password
        ports:
        - containerPort: 8000
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
