kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-pv-claim
  namespace: poornima-dev
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi