groups:
- name: delivery
  jobs:
  - build
  - tag
  - push
  - deploy

resources:
- name: git-wordpressapp
  type: git
  source:
    uri: https://github.com/poornima-moj/wordpressapp.git
    branch: master
- name: wordpressapp-docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    repository: {{docker-hub-repository}}
    password: {{docker-hub-password}}

jobs:
- name: build
  serial: true
  public: true
  plan:
  - get: git-wordpressapp
    # trigger: true
  - put: wordpressapp-docker-image
    params:
      build: ./git-wordpressapp
