name: deploy to development on merge to master branch
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Declare variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag poornimak/wordpressapp:${{steps.vars.outputs.sha_short}}
      - name: Push the tagged Docker image
        run: docker push poornimak/wordpressapp:${{steps.vars.outputs.sha_short}}
      - name: Deploy to development
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: set image --record deployment/my-wpapp-helm-deploy wordpress=poornimak/wordpressapp:${{steps.vars.outputs.sha_short}} -n poornima-dev
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
          KUBECTL_VERSION: "1.15"
        with:
          args: '"rollout status deployment/my-wpapp-helm-deploy"'