name: 'Deploy'     # Name of the action.
on: ['deployment'] # Listen for deployment events.
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'  # Checkout the repository code.
      uses: 'actions/checkout@v1'

    - name: 'Deploy'
      uses: 'poornima-krishnasamy/wordpressapp/helm-deploy@master'
      with:
        token: '${{ github.token }}'
        chart: 'helm-deploy'
        namespace: poornima-dev
        release: dev-myapp
        value-files: './config/development.yaml'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'