on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: poornima-krishnasamy/wordpressapp/reject-escalated-privileges@add-reject-escalated-priv