on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ministryofjustice/github-actions/reject-escalated-privileges@add-reject-escalated-priv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}