jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ministryofjustice/cloud-platform-tools}
      params:
        HELLO: ((hello))
      run:
        path: /bin/sh
        args: ["-c", "AWS_REGION=eu-west-2; aws secretsmanager list-secrets --region eu-west-2; echo $HELLO"]